### ISSUE TITLE
Error handling with createStream

### ISSUE THREAD

**Issue by mikehardenize** [alabianca/xml-to-json#1]
How do I do error handling when using the createStream form? If the XML is invalid, it just seems to pass the invalid xml through to the next stream, rather than failing...

**Comment by alabianca** [comment]
@mikehardenize Can you give me an example what you are currently trying to do for error handling? And the xml you are passing?

You should generally do standard stream error handling to catch an error. You can do: ```stream.on('error',(err)=>{})``` 
Then on the error event unpipe the next stream. ```stream.unpipe()``` . Unfortunately doing error handling on stream pipelines is tricky.

I will look more into it when I get home from work. 

If you have a suggestion on how the errors should be handled feel free to give a possible solution and we work it out.

**Comment by mikehardenize** [comment]
Hi. `stream.on('error',(err)=>{})` is exactly what I tried, but it never triggered that handler. I attempted to trigger an error by simply removing the closing angle bracket for the entire XML. All that happened is the next stream in the chain received the raw XML instead of the JSON.

**Comment by alabianca** [comment]
Thanks @mikehardenize . 
I was able to recreate it. Seems to be an issue with the validator. I am fixing it.

**Comment by alabianca** [comment]
Finally had some time to get a fix going for this. The fix is currently on branch `xmlToJsonStream/patch/1.0.3` . All tests passed. Will try to have it published to npm mid this week. 
Feel free to test it out before I merge.

**Comment by mikehardenize** [comment]
Thank you for fixing this
