### ISSUE TITLE
Repetitive xml tag occurs Illegal start of XML tag error in stream mode

### ISSUE THREAD

**Issue by clequinio5** [alabianca/xml-to-json#4]
`<acces>
     <acces>test</acces>
</acces>`

-> Error: Invalid XML. Illegal start of XML tag

`<acces>
    <acces1>test</acces1>
</acces>`

->Same but when comment the code lines error, pass

**Comment by alabianca** [comment]
Looking into it

**Comment by alabianca** [comment]
I have an idea what is causing it. See branch [xmlToJsonStream/patch/1.0.4](https://github.com/alabianca/xml-to-json/tree/xmlToJsonStream/patch/1.0.4) . I need to run through some testing before I publish this though. There are failing test cases at the moment.

**Comment by alabianca** [comment]
Fixed in v1.0.4
